# Generated by Django 4.1.4 on 2023-01-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_catagory_tag_posttag_postcatagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_id',
        ),
    ]
