# Generated by Django 4.1.4 on 2023-01-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priduct_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_descriptions', models.TextField(max_length=255)),
                ('product_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
