# Generated by Django 4.1.4 on 2023-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_descriptions',
            field=models.CharField(max_length=255),
        ),
    ]
