# Generated by Django 4.1.4 on 2023-01-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priduct_id',
            new_name='product_id',
        ),
    ]
