# Generated by Django 4.1.4 on 2023-01-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_priduct_id_product_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
